version: '3.8'

services:
    backend:
        env_file: .env
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: 'multi-requests/backend'
        ports:
            - '5000:5000'
    frontend:
        build:
            context: ./client
            dockerfile: ./Dockerfile
        image: 'multi-requests/frontend'
        ports:
            - '3000:3000'
        links:
            - 'backend:be'
    postgres:
        container_name: postgres
        hostname: postgres
        image: 'postgres:12'
        ports:
            - '5432:5432'
        restart: always
        env_file: .env
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data
